global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: device
    static_configs:
      - targets: ['device:3000']

  - job_name: edge
    static_configs:
      - targets: ['edge:3000']

  - job_name: core-1
    static_configs:
      - targets: ['core-1:4000']
        labels: { replica: core-1 }

  - job_name: core-2
    static_configs:
      - targets: ['core-2:4000']
        labels: { replica: core-2 }

  - job_name: core-ml
    static_configs:
      - targets: ['core-ml:5000']

  - job_name: cloud
    static_configs:
      - targets: ['cloud:6000']

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']
